#!/usr/bin/env bash                                                                                                                   
#displays Best School 10 times (until)

i=0

until [ $i -gt 10 ]

do

   echo 'Best School'
        ((i ++))

done
