#!/usr/bin/env bash
#Bash script that loops from 1 to 10
i=0

while [ $i -lt 10 ] ; do

 if [ $i -eq 2 ] ; 

then 

 echo -e 'Best School\nbad luck' 

elif [ $i -eq 7 ]

then

echo 'good luck'

else 

echo 'Best School'

fi

((i=i+1))

done
