#!/usr/bin/env bash
#cript that displays numbers from 1 to 20 

i=1

while [ $i -lt 21 ] ; do

 echo " $i "

  case "$i" in

	  "4" )
		  
	 echo "bad luck from china" 

	 ;;

        "9" )
		
         echo " bad luck from Japan"

        ;;
       
	"17"

	echo "bad luck from Italy "

        esac

	((i+=1))	
done	
