#!/usr/bin/env bash
#cript that displays numbers from 1 to 20 

i=1

while [ $i -lt 21 ] ; do

 echo " $i "

  case "$i" in

	  "4" )
		  
	 echo "bad luck fron china" 

	 ;;

        "9" )
		
         echo " bad luck from juapan"

        ;;
       
        esac

	((i+=1))	
done	
