#!/usr/bin/env bash
#script that Displays To infinity and beyond indefinitely

file=/var/run/myscript.pid

echo $$ >> $file

trap 'echo I hate the kill command; sudo rm $file; exit' SIGTERM

trap 'echo Y U no love me?!' SIGINT

trap 'sudo rm $file; exit ' SIGQUIT

while ((1)); do

echo "To infinity and beyond"

sleep 2

done  
